// PDF Template Builder
import { marked } from 'marked';
import { pdfStyles, formatWorkflowType, getWorkflowAccentColor } from './styles';

interface ReportData {
  id: string;
  title: string;
  workflowType: string;
  companyName?: string;
  generatedContent: Record<string, { section: string; content: string; metadata: any }>;
  createdAt: Date;
  completedAt?: Date;
}

const formatSectionName = (sectionKey: string): string => {
  return sectionKey
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

const formatDate = (date: Date): string => {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
};

const buildCoverPage = (report: ReportData): string => {
  const workflowDisplay = formatWorkflowType(report.workflowType);
  const companyName = report.companyName || (report as any).inputData?.companyName || '';

  return `
    <div class="cover-page">
      <div class="cover-type-badge">${workflowDisplay}</div>
      <h1 class="cover-title">${escapeHtml(report.title)}</h1>
      ${companyName ? `<div class="cover-company">${escapeHtml(companyName)}</div>` : ''}
      <div class="cover-meta">
        <div class="cover-meta-item">Generated: ${formatDate(new Date(report.completedAt || report.createdAt))}</div>
        <div class="cover-meta-item">Report ID: ${report.id}</div>
      </div>
    </div>
  `;
};

const buildTableOfContents = (sections: string[]): string => {
  const items = sections.map((section, index) => `
    <li class="toc-item">
      <a href="#section-${index}">${formatSectionName(section)}</a>
      <span class="toc-page-num">${index + 2}</span>
    </li>
  `).join('');

  return `
    <div class="toc">
      <h1 class="toc-title">Table of Contents</h1>
      <ul class="toc-list">
        ${items}
      </ul>
    </div>
  `;
};

const buildSection = (
  sectionKey: string,
  sectionData: { section: string; content: string; metadata: any },
  index: number
): string => {
  const htmlContent = marked.parse(sectionData.content) as string;

  return `
    <div class="report-section" id="section-${index}">
      <h2>${formatSectionName(sectionKey)}</h2>
      <div class="section-content">
        ${htmlContent}
      </div>
    </div>
  `;
};

const buildFooter = (report: ReportData): string => {
  return `
    <div class="report-footer">
      <p>Generated by IIoT Account Intelligence | ${formatDate(new Date())} | Report ID: ${report.id}</p>
    </div>
  `;
};

const escapeHtml = (text: string): string => {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
};

export const buildPdfHtml = (report: ReportData): string => {
  const workflowClass = `workflow-${report.workflowType.toLowerCase().replace(/_/g, '-')}`;
  const sections = Object.keys(report.generatedContent || {});

  const coverPage = buildCoverPage(report);
  const toc = sections.length > 1 ? buildTableOfContents(sections) : '';

  const sectionsHtml = Object.entries(report.generatedContent || {})
    .map(([key, data], index) => buildSection(key, data, index))
    .join('\n');

  const footer = buildFooter(report);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(report.title)}</title>
  <style>
    ${pdfStyles}
  </style>
</head>
<body class="report-document ${workflowClass}">
  ${coverPage}
  ${toc}
  <div class="report-content">
    ${sectionsHtml}
  </div>
  ${footer}
</body>
</html>
  `.trim();
};

export { pdfStyles, formatWorkflowType, getWorkflowAccentColor, formatSectionName };
